#pragma once
#include <GL/glew.h>
#include "../JuceLibraryCode/JuceHeader.h"
#include <stdexcept>
#include <memory>
#include <fstream>
#include <cmath>
#include <vector>
#include <cassert>
#include <string>
#include <stdint.h>
#include <map>
#include "matrixd.h"